name: Hello World

on:
  repository_dispatch:
    types: helloworld

jobs:
  hello-world:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run PowerShell Hello World script
      run: Write-Output 'Hello World!'
    - name: Run a multi-line PowerShell script
      run: |
        $PSVersionTable;
        Get-Module -ListAvailable | Format-Table name,version;
