name: Hello World script

on:
  repository_dispatch:
    types: script

jobs:
  hello-world-script:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run PowerShell Hello World script
      run: pwsh -command ".\$GITHUB_WORKSPACE\Hello-World.ps1"
