# File: .github/workflows/self-hosted.yml

on: [push]

name: Azure System-assigned Managed Identity sample

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:
    
    - name: Login via Az module
      uses: jpda/login@v1
      with:
        enable-managed-identity: true
    
    - name: Azure CLI script
      run: |
        az group list -o table
